SHOW STAGES IN SCHEMA SNOWFLAKE.SNOWPARK;

GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER
TO ROLE ACCOUNTADMIN;

SHOW STREAMLITS;

ALTER STREAMLIT USER$SRILATHA.PUBLIC."STB7B1D819CA07AF1742FCD80A806D63CED60E6032"
SET ARTIFACT_REPOSITORIES = (SNOWFLAKE.SNOWPARK.PYPI_SHARED_REPOSITORY);

SHOW STREAMLITS;

SHOW COMPUTE POOLS;

SHOW SERVICES IN COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU;

DROP STREAMLIT ML_WORKFLOW_DB.ML_SCHEMA.HOUSE_PRICE_PREDICITON;
